name: Api

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: php-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dockerize
        run: wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && rm dockerize-linux-amd64-v0.6.1.tar.gz

      - name: Docker build & run
        run: docker-compose build api && docker-compose up -d api

      - name: Run Composer install
        run: docker-compose exec -T api bash -c "composer install"

      - name: Run tests
        run: docker-compose exec -T api bash -c "composer run test"

  linter:
    name: php-lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run linter:check


